const empList = [
    {
      id: "0001",
      Full_Name: "Swagat",
      Gender: "Male",
      age: "20",
      Curent_Project: "Java",
      Reporting_to: "Lead1",
      Designation: "Developer",
      Department: "HR",
    },
    {
      id: "0002",
      Full_Name: "Sangeeta",
      Gender: "Female",
      age: "25",
      Curent_Project: "React",
      Reporting_to: "Lead2",
      Designation: "Test Eng",
      Department: "BD",
    },
    {
      id: "0003",
      Full_Name: "Solo",
      Gender: "Male",
      age: "34",
      Curent_Project: "node",
      Reporting_to: "Lead3",
      Designation: "Manager",
      Department: "HR",
    },
    {
      id: "0004",
      Full_Name: "Solo",
      Gender: "Male",
      age: "34",
      Curent_Project: "node",
      Reporting_to: "Lead3",
      Designation: "Manager",
      Department: "Testing",
    },
    {
      id: "0005",
      Full_Name: "Solo",
      Gender: "Female",
      age: "34",
      Curent_Project: "node",
      Reporting_to: "Lead3",
      Designation: "Manager",
      Department: "BD",
    },
    {
      id: "0006",
      Full_Name: "Solo",
      Gender: "Male",
      age: "34",
      Curent_Project: "node",
      Reporting_to: "Lead3",
      Designation: "Manager",
      Department: "BD",
    },
    {
      id: "0007",
      Full_Name: "Solo",
      Gender: "Male",
      age: "34",
      Curent_Project: "node",
      Reporting_to: "Lead3",
      Designation: "Manager",
      Department: "Technical",
    }, 
    {
      id: "0008",
      Full_Name: "Bad boy",
      Gender: "Female",
      age: "34",
      Curent_Project: "Whatsapp",
      Reporting_to: "Lead3",
      Designation: "Test Engineer",
      Department: "Testing",
    }, 
    {
      id: "0009",
      Full_Name: "Dotk",
      Gender: "Male",
      age: "34",
      Curent_Project: "Facebook",
      Reporting_to: "Lead3",
      Designation: "Trainee",
      Department: "Technical",
    }, 
    {
      id: "0010",
      Full_Name: "Solo",
      Gender: "Male",
      age: "34",
      Curent_Project: "node",
      Reporting_to: "Lead3",
      Designation: "Manager",
      Department: "HR",
    }
  ]
  export default empList;